#! /usr/bin/env zsh

SESSION="revbayes-env"

SESSIONEXISTS=$(tmux list-sessions | grep $SESSION)

if [ "$SESSIONEXISTS" = "" ]; then

    cd $HOME/projects/revbayes
    tmux new-session   -d -s $SESSION

    # Select pane 0 and set dir
    tmux selectp       -t 0
    #tmux send-keys "clear" C-m

    # Split pane 0 horizontal by 35%, start nix-shell
    tmux splitw        -h -p 65 -c "#{pane_current_path}"
    sleep 0.1
    tmux send-keys     "nix-shell; cd projects/cmake" C-m
    sleep 0.1

    # Select pane 1 and split vertically by 80%
    tmux selectp       -t 1
    tmux splitw        -v -p 20 -c "#{pane_current_path}"
    tmux send-keys     "cd ../../" C-m

    # create a new window called scratch
    tmux new-window    -t $SESSION:1 -n rev-scripts

    # return to main window and start vim
    tmux select-window -t $SESSION:0
    tmux select-pane   -t 0

fi

tmux attach-session -t $SESSION

