#! /usr/bin/env zsh

BASEDIR="$HOME/idrisDev/GraphDB"

tmux new-window   -n "graphdb"
tmux send-keys    "cd $BASEDIR" C-m
tmux split-window -h -c "#{pane_current_path}"
tmux send-keys    "cd $BASEDIR" C-m
tmux send-keys    "nix-shell" C-m
tmux resize-pane  -L 12
tmux split-window -v -c "#{pane_current_path}"
tmux send-keys    "cd $BASEDIR" C-m
tmux select-pane  -t 0
tmux send-keys    "nvim test/UniProtTest.idr src/Database/UniProt/*.idr" C-m


